use aes_gcm::{
    aead::{Aead, KeyInit},
    Aes256Gcm, Nonce,
};
use wasm_bindgen::prelude::*;
use crate::encrypt::{sdk_err, SdkErrorCode};

/// A stateful encryptor for processing large files in chunks.
/// Automatically increments an internal counter mixed with the base nonce.
#[wasm_bindgen]
pub struct ChunkEncryptor {
    cipher: Aes256Gcm,
    base_nonce: [u8; 12],
    counter: u32,
}

#[wasm_bindgen]
impl ChunkEncryptor {
    #[wasm_bindgen(constructor)]
    pub fn new(aes_key: &[u8], base_nonce: &[u8]) -> Result<ChunkEncryptor, JsValue> {
        if aes_key.len() != 32 {
            return Err(sdk_err(
                SdkErrorCode::InvalidAesKey,
                &format!("Expected 32 bytes, got {}", aes_key.len()),
            ));
        }
        if base_nonce.len() != 12 {
            return Err(sdk_err(
                SdkErrorCode::InvalidNonce,
                &format!("Expected 12 bytes, got {}", base_nonce.len()),
            ));
        }

        let cipher = Aes256Gcm::new_from_slice(aes_key)
            .map_err(|e| sdk_err(SdkErrorCode::InvalidAesKey, &e.to_string()))?;
        
        let mut nonce = [0u8; 12];
        nonce.copy_from_slice(base_nonce);

        Ok(Self {
            cipher,
            base_nonce: nonce,
            counter: 0,
        })
    }

    pub fn encrypt_chunk(&mut self, chunk: &[u8]) -> Result<Vec<u8>, JsValue> {
        let mut current_nonce = self.base_nonce;
        let counter_bytes = self.counter.to_be_bytes();
        
        // XOR the counter into the last 4 bytes of the nonce
        for i in 0..4 {
            current_nonce[8 + i] ^= counter_bytes[i];
        }
        self.counter += 1;

        let nonce = Nonce::from_slice(&current_nonce);
        self.cipher
            .encrypt(nonce, chunk)
            .map_err(|_| sdk_err(SdkErrorCode::AesEncryptFailed, "Chunk encryption failed"))
    }
}

/// A stateful decryptor for processing large files in chunks.
/// Must be used with chunks generated by `ChunkEncryptor` in the same order.
#[wasm_bindgen]
pub struct ChunkDecryptor {
    cipher: Aes256Gcm,
    base_nonce: [u8; 12],
    counter: u32,
}

#[wasm_bindgen]
impl ChunkDecryptor {
    #[wasm_bindgen(constructor)]
    pub fn new(aes_key: &[u8], base_nonce: &[u8]) -> Result<ChunkDecryptor, JsValue> {
        if aes_key.len() != 32 {
            return Err(sdk_err(
                SdkErrorCode::InvalidAesKey,
                &format!("Expected 32 bytes, got {}", aes_key.len()),
            ));
        }
        if base_nonce.len() != 12 {
            return Err(sdk_err(
                SdkErrorCode::InvalidNonce,
                &format!("Expected 12 bytes, got {}", base_nonce.len()),
            ));
        }

        let cipher = Aes256Gcm::new_from_slice(aes_key)
            .map_err(|e| sdk_err(SdkErrorCode::InvalidAesKey, &e.to_string()))?;
        
        let mut nonce = [0u8; 12];
        nonce.copy_from_slice(base_nonce);

        Ok(Self {
            cipher,
            base_nonce: nonce,
            counter: 0,
        })
    }

    pub fn decrypt_chunk(&mut self, encrypted_chunk: &[u8]) -> Result<Vec<u8>, JsValue> {
        let mut current_nonce = self.base_nonce;
        let counter_bytes = self.counter.to_be_bytes();
        
        for i in 0..4 {
            current_nonce[8 + i] ^= counter_bytes[i];
        }
        self.counter += 1;

        let nonce = Nonce::from_slice(&current_nonce);
        self.cipher
            .decrypt(nonce, encrypted_chunk)
            .map_err(|_| sdk_err(SdkErrorCode::AesDecryptFailed, "Chunk decryption failed"))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use wasm_bindgen_test::*;

    #[wasm_bindgen_test]
    fn test_chunk_streaming() {
        let aes_key = vec![0u8; 32];
        let base_nonce = vec![1u8; 12];
        
        let mut encryptor = ChunkEncryptor::new(&aes_key, &base_nonce).unwrap();
        let mut decryptor = ChunkDecryptor::new(&aes_key, &base_nonce).unwrap();
        
        let chunk1_plain = b"Hello, World!";
        let chunk2_plain = b"Streaming AES-GCM";
        
        let chunk1_cipher = encryptor.encrypt_chunk(chunk1_plain).unwrap();
        let chunk2_cipher = encryptor.encrypt_chunk(chunk2_plain).unwrap();
        
        assert_ne!(chunk1_plain, &chunk1_cipher[..]);
        assert_ne!(chunk2_plain, &chunk2_cipher[..]);
        
        let chunk1_decrypted = decryptor.decrypt_chunk(&chunk1_cipher).unwrap();
        let chunk2_decrypted = decryptor.decrypt_chunk(&chunk2_cipher).unwrap();
        
        assert_eq!(chunk1_plain, &chunk1_decrypted[..]);
        assert_eq!(chunk2_plain, &chunk2_decrypted[..]);
    }
}
